CREATE DATABASE IF NOT EXISTS ESCOLA;

USE ESCOLA;

CREATE TABLE IF NOT EXISTS CIDADES
(ID SMALLINT  NOT NULL AUTO_INCREMENT PRIMARY KEY, 
 NOME CHAR(40) NOT NULL,
 UF CHAR(02) NOT NULL);
 
 CREATE TABLE IF NOT EXISTS NUCLEOS
(ID TINYINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
 NUCLEO CHAR(20) NOT NULL);
 
 CREATE TABLE IF NOT EXISTS DISCIPLINAS
(ID TINYINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
 DISCIPLINA CHAR(30) NOT NULL,
 ID_NUCLEO TINYINT NOT NULL);
 
 CREATE TABLE IF NOT EXISTS CURSOS
(ID TINYINT  NOT NULL AUTO_INCREMENT PRIMARY KEY, 
 CURSO CHAR(30) NOT NULL,
 SEMESTRES TINYINT NOT NULL);

CREATE TABLE IF NOT EXISTS ALUNOS 
(ID  INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
 NOME CHAR(50) NOT NULL, 
 RG CHAR(12) NOT NULL,
 CPF CHAR(14) NOT NULL,
 DATA_NASCIMENTO DATE NOT NULL,
 ENDERECO CHAR (50) NOT NULL,
 NUMERO SMALLINT NOT NULL,
 COMPLEMENTO VARCHAR (50),
 BAIRRO CHAR(40) NOT NULL, 
 ID_CIDADE SMALLINT NOT NULL,
 CEP CHAR (10) NOT NULL,
 TELEFONE CHAR(13) NOT NULL,
 CELULAR CHAR(14) NOT NULL, 
 PAI CHAR(50) NOT NULL, 
 MAE CHAR(50) NOT NULL,
 EMAIL VARCHAR(50) NOT NULL,
 ATIVO BOOL NOT NULL);
 
CREATE TABLE IF NOT EXISTS PROFESSORES
(ID  INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
 NOME CHAR(50) NOT NULL, 
 RG CHAR(12) NOT NULL,
 CPF CHAR(14) NOT NULL,
 DATA_NASCIMENTO DATE NOT NULL,
 ENDERECO CHAR (50) NOT NULL,
 NUMERO SMALLINT NOT NULL, 
 COMPLEMENTO VARCHAR (50),
 BAIRRO CHAR(40) NOT NULL, 
 ID_CIDADE SMALLINT NOT NULL,
 CEP CHAR (10) NOT NULL,
 TELEFONE CHAR(13) NOT NULL,
 CELULAR CHAR(14) NOT NULL, 
 DATA_CONTRATO DATE NOT NULL,
 EMAIL VARCHAR(50) NOT NULL,
 ATIVO BOOL NOT NULL);
