Insert into cidades (NOME, UF) values ('RIO BRANCO', 'AC');
Insert into cidades (NOME, UF) values ('MACEIO', 'AL');
Insert into cidades (NOME, UF) values ('AMAPA', 'AP');
Insert into cidades (NOME, UF) values ('MANAUS', 'AM');
Insert into cidades (NOME, UF) values ('SALVADOR', 'BA');
Insert into cidades (NOME, UF) values ('FORTALEZA', 'CE');
Insert into cidades (NOME, UF) values ('BRASILIA', 'DF');
Insert into cidades (NOME, UF) values ('VITORIA', 'ES');
Insert into cidades (NOME, UF) values ('GOIANIA', 'GO');
Insert into cidades (NOME, UF) values ('SAO LUIS', 'MA');
Insert into cidades (NOME, UF) values ('CUIABA', 'MT');
Insert into cidades (NOME, UF) values ('CAMPO GRANDE', 'MS');
Insert into cidades (NOME, UF) values ('BELO HORIZONTE', 'MG');
Insert into cidades (NOME, UF) values ('BELEM', 'PA');
Insert into cidades (NOME, UF) values ('JOAO PESSOA', 'PB');
Insert into cidades (NOME, UF) values ('CURITIBA', 'PR');
Insert into cidades (NOME, UF) values ('RECIFE', 'PE');
Insert into cidades (NOME, UF) values ('TERESINA', 'PI');
Insert into cidades (NOME, UF) values ('RIO DE JANEIRO', 'RJ');
Insert into cidades (NOME, UF) values ('NATAL', 'RN');
Insert into cidades (NOME, UF) values ('PORTO ALEGRE', 'RS');
Insert into cidades (NOME, UF) values ('PORTO VELHO','RO');
Insert into cidades (NOME, UF) values ('FLORIANOPOLES', 'SC');
Insert into cidades (NOME, UF) values ('SAO PAULO', 'SP');
Insert into cidades (NOME, UF) values ('ARACAJU', 'SE');
Insert into cidades (NOME, UF) values ('PALMAS' 'TO');