CREATE DATABASE escola;
USE escola;
CREATE TABLE IF NOT EXISTS escola.cidades
(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME CHAR(50),
UF CHAR(2));
CREATE TABLE IF NOT EXISTS escola.nucleos
(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME CHAR(50),
nucleo CHAR(20));
CREATE TABLE IF NOT EXISTS escola.cursos
(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
curso CHAR(20),
semestres integer);
CREATE TABLE IF NOT EXISTS escola.disciplinas
(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
disciplina CHAR(20),
ID_nucleo integer);